# Generated by Django 3.2.6 on 2021-09-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batsu_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.FloatField(max_length=5)),
                ('y_axis', models.FloatField(max_length=5)),
                ('z_axis', models.FloatField(max_length=5)),
                ('temp', models.FloatField(max_length=5)),
                ('dateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Batsu01',
            },
        ),
        migrations.CreateModel(
            name='Batsu_02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.FloatField(max_length=5)),
                ('y_axis', models.FloatField(max_length=5)),
                ('z_axis', models.FloatField(max_length=5)),
                ('temp', models.FloatField(max_length=5)),
                ('dateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Batsu02',
            },
        ),
        migrations.CreateModel(
            name='Batsu_03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.FloatField(max_length=5)),
                ('y_axis', models.FloatField(max_length=5)),
                ('z_axis', models.FloatField(max_length=5)),
                ('temp', models.FloatField(max_length=5)),
                ('dateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Batsu03',
            },
        ),
        migrations.CreateModel(
            name='Batsu_04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.FloatField(max_length=5)),
                ('y_axis', models.FloatField(max_length=5)),
                ('z_axis', models.FloatField(max_length=5)),
                ('temp', models.FloatField(max_length=5)),
                ('dateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Batsu04',
            },
        ),
        migrations.CreateModel(
            name='Batsu_05',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.FloatField(max_length=5)),
                ('y_axis', models.FloatField(max_length=5)),
                ('z_axis', models.FloatField(max_length=5)),
                ('temp', models.FloatField(max_length=5)),
                ('dateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Batsu05',
            },
        ),
    ]
